using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Content.Client.Stylesheets;


namespace Content.Client.Silicons.StationAi;
[GenerateTypedNameReferences]
public sealed class StationAIWarpMenu_xaml : UIWidget
{

}
